/**
 * Stable machine-readable error codes. Clients branch on these, never on the
 * message text, so a code is part of the API contract: add freely, never
 * repurpose or rename.
 */
export const ErrorCode = {
  // generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  CONFLICT: 'CONFLICT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DEPENDENCY_FAILURE: 'DEPENDENCY_FAILURE',

  // authentication
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_NOT_ACTIVATED: 'ACCOUNT_NOT_ACTIVATED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  API_KEY_INVALID: 'API_KEY_INVALID',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  PASSWORD_REUSED: 'PASSWORD_REUSED',

  // email OTP second factor
  MFA_REQUIRED: 'MFA_REQUIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_ATTEMPTS_EXCEEDED: 'OTP_ATTEMPTS_EXCEEDED',
  OTP_RESEND_COOLDOWN: 'OTP_RESEND_COOLDOWN',
  OTP_RESEND_LIMIT: 'OTP_RESEND_LIMIT',

  // federated sign-in (SSO)
  SSO_PROVIDER_UNAVAILABLE: 'SSO_PROVIDER_UNAVAILABLE',
  SSO_STATE_INVALID: 'SSO_STATE_INVALID',
  SSO_STATE_EXPIRED: 'SSO_STATE_EXPIRED',
  SSO_EXCHANGE_FAILED: 'SSO_EXCHANGE_FAILED',
  SSO_IDENTITY_REJECTED: 'SSO_IDENTITY_REJECTED',
  SSO_NO_ACCOUNT: 'SSO_NO_ACCOUNT',
  SSO_IDENTITY_MISMATCH: 'SSO_IDENTITY_MISMATCH',
  SSO_LOGIN_REQUIRED: 'SSO_LOGIN_REQUIRED',
  SSO_LAST_CREDENTIAL: 'SSO_LAST_CREDENTIAL',

  // invitations
  INVITATION_INVALID: 'INVITATION_INVALID',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_ALREADY_ACCEPTED: 'INVITATION_ALREADY_ACCEPTED',
  INVITATION_REVOKED: 'INVITATION_REVOKED',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',

  // password reset
  RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID',
  RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED',

  // guardrails
  LAST_SUPER_ADMIN: 'LAST_SUPER_ADMIN',
  SYSTEM_ROLE_IMMUTABLE: 'SYSTEM_ROLE_IMMUTABLE',
  ROLE_IN_USE: 'ROLE_IN_USE',
  USER_HAS_OPEN_TICKETS: 'USER_HAS_OPEN_TICKETS',
  SELF_ACTION_FORBIDDEN: 'SELF_ACTION_FORBIDDEN',
  EMAIL_DELIVERY_FAILED: 'EMAIL_DELIVERY_FAILED',

  // data integrity
  UNIQUE_VIOLATION: 'UNIQUE_VIOLATION',
  FOREIGN_KEY_VIOLATION: 'FOREIGN_KEY_VIOLATION',

  // idempotency
  IDEMPOTENCY_KEY_IN_PROGRESS: 'IDEMPOTENCY_KEY_IN_PROGRESS',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
